services:
  db-notifications:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notifications
    volumes:
      - notifications:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

  notifications:
    build:
      dockerfile: ./Dockerfile
    environment:
      api_url: /api/v1
    ports:
      - 5055:8080
    depends_on:
      db-notifications:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MiB

volumes:
  notifications: