services:
  db-products:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 6061:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MiB
  
  products:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      db-products:
        condition: service_healthy
    ports:
      - 6060:80
    volumes:
      - C:\Users\yadim\YandexDisk\labs\semenov\labs2-5\product_service_cpp\saved_files:/usr/local/apache2/saved_files
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MiB

volumes:
  db: